checks:
    php:
        code_rating: true
        duplication: true
filter:
    paths:
        - "src/app"
    excluded_paths:
        - "src/app/Block/DataObject.php" # Magento File.
        - "src/app/Command" # This is goop and not business logic.
build:
    environment:
        php:
            version: 7.0
    tests:
            override:
                -
                    command: phpunit --coverage-clover=./test-results/clover.xml
                    coverage:
                        file: ./test-results/clover.xml
                        format: php-clover
